import { randomUUID } from "node:crypto";
import { chmod, lstat, mkdir, readFile, realpath, rename, rm, symlink, writeFile } from "node:fs/promises";
import { basename, dirname, join } from "node:path";
import {
  type CliProxySecrets,
  type CliProxyState,
  MODEL_NAME_RE,
  cliproxyDir,
  cliproxyHomeDir,
  cliproxyTokenFile
} from "@orquester/config";

/** Marker file written into each managed home; content is the entry id. */
export const CLIPROXY_HOME_MARKER = ".orq-cliproxy-home";

/**
 * Atomic 0600/0700 write that refuses to be redirected through a symlinked
 * target (parent realpath-canonicalized, final path rebuilt from real parent).
 */
async function writeHardened(file: string, content: string, mode: number, dirMode = 0o700): Promise<void> {
  const parent = dirname(file);
  await mkdir(parent, { recursive: true, mode: dirMode });
  const realParent = await realpath(parent);
  const target = join(realParent, basename(file));
  let st: Awaited<ReturnType<typeof lstat>> | null = null;
  try {
    st = await lstat(target);
  } catch {
    st = null;
  }
  if (st?.isSymbolicLink()) {
    throw new Error(`refusing to write through a symlinked target: ${file}`);
  }
  const tmp = `${target}.${randomUUID()}.tmp`;
  try {
    await writeFile(tmp, content, { encoding: "utf8", mode });
    await chmod(tmp, mode).catch(() => undefined);
    await rename(tmp, target);
  } catch (error) {
    await rm(tmp, { force: true }).catch(() => undefined);
    throw error;
  }
}

function assertModel(name: string, label: string): void {
  if (!MODEL_NAME_RE.test(name)) {
    throw new Error(`invalid ${label} model name: ${JSON.stringify(name)}`);
  }
}

/**
 * Render the proxy's `config.yaml`. The proxy runs with cwd = the cliproxy dir,
 * so `auth-dir`/log paths are relative. The `openai-compatibility` provider
 * (with the `kimi-k3 → moonshotai/kimi-k3` alias) is emitted only when an
 * OpenRouter key is configured — no key means no block and no alias.
 */
export function renderConfigYaml(secrets: CliProxySecrets, state: CliProxyState): string {
  const lines: string[] = [
    "# generated by orquester CliProxyManager — do not edit",
    'host: "127.0.0.1"',
    `port: ${state.port}`,
    'auth-dir: "auth"',
    "logging:",
    '  dir: "logs"',
    "  request-log: true",
    // request/response BODIES stay off — they would capture prompts + completions.
    "  log-request-body: false",
    "  log-response-body: false",
    "remote-management:",
    `  secret-key: ${JSON.stringify(secrets.managementSecret)}`,
    "  allow-remote: false",
    "api-keys:",
    `  - ${JSON.stringify(secrets.apiKey)}`
  ];
  if (secrets.openRouterKey) {
    lines.push(
      "openai-compatibility:",
      '  - name: "openrouter"',
      '    base-url: "https://openrouter.ai/api/v1"',
      "    api-key-entries:",
      `      - api-key: ${JSON.stringify(secrets.openRouterKey)}`,
      "        models:",
      '          - name: "moonshotai/kimi-k3"',
      '            alias: "kimi-k3"'
    );
  }
  return lines.join("\n") + "\n";
}

function renderEnvFile(entries: Array<[string, string]>): string {
  return entries.map(([k, v]) => `${k}=${v}`).join("\n") + "\n";
}

/** POSIX-sh wrapper: parses the env file as data (no `source`), reads the token
 *  file, and (for claudex) accepts a validated `--model`, then `exec claude`. */
function renderWrapper(entryId: "claudex" | "claudemix", envFile: string, tokenFile: string): string {
  return [
    "#!/bin/sh",
    "# generated by orquester CliProxyManager — do not edit",
    "set -eu",
    `ENV_FILE="${envFile}"; TOKEN_FILE="${tokenFile}"`,
    "while IFS='=' read -r k v; do",
    "  case \"$k\" in ''|'#'*) continue;; esac",
    "  case \"$k\" in *[!A-Za-z0-9_]*) continue;; esac",
    '  export "$k=$v"',
    'done < "$ENV_FILE"',
    'ANTHROPIC_AUTH_TOKEN="$(cat "$TOKEN_FILE")"; export ANTHROPIC_AUTH_TOKEN',
    `if [ "${entryId}" = "claudex" ] && [ "\${1:-}" = "--model" ]; then`,
    "  case \"${2:-}\" in *[!A-Za-z0-9._/-]*|'') echo \"claudex: invalid --model\" >&2; exit 2;; esac",
    '  export ANTHROPIC_MODEL="$2" CLAUDE_CODE_SUBAGENT_MODEL="$2"; shift 2',
    "fi",
    'exec claude "$@"',
    ""
  ].join("\n");
}

/**
 * Rewrite every derived projection from the authoritative secrets + state:
 * `config.yaml` (0600), `token` (0600), both entry env files under
 * `<daemonDir>/env/` (0600 in a 0700 dir), and both wrapper bins under
 * `<appdir>/.npm-global/bin/` (0700). Model names are validated before any
 * write, so a poisoned model can never reach an env file or shell.
 */
export async function writeProjections(
  daemonDir: string,
  secrets: CliProxySecrets,
  state: CliProxyState
): Promise<void> {
  assertModel(state.defaultModel, "default");
  assertModel(state.backgroundModel, "background");

  const dir = cliproxyDir(daemonDir);
  const baseUrl = `http://127.0.0.1:${state.port}`;
  const appdir = dirname(daemonDir);
  const binDir = join(appdir, ".npm-global", "bin");
  const envDir = join(daemonDir, "env");
  const tokenFile = cliproxyTokenFile(daemonDir);
  const claudexHome = cliproxyHomeDir(daemonDir, "claudex");
  const claudemixHome = cliproxyHomeDir(daemonDir, "claudemix");

  await writeHardened(join(dir, "config.yaml"), renderConfigYaml(secrets, state), 0o600);
  await writeHardened(tokenFile, `${secrets.apiKey}\n`, 0o600);

  const claudexEnv = renderEnvFile([
    ["ANTHROPIC_BASE_URL", baseUrl],
    ["ANTHROPIC_MODEL", state.defaultModel],
    ["ANTHROPIC_DEFAULT_HAIKU_MODEL", state.backgroundModel],
    ["CLAUDE_CODE_SUBAGENT_MODEL", state.defaultModel],
    ["CLAUDE_CODE_ALWAYS_ENABLE_EFFORT", "1"],
    ["CLAUDE_CODE_MAX_TOOL_USE_CONCURRENCY", "3"],
    ["ENABLE_TOOL_SEARCH", "false"],
    ["CLAUDE_CODE_NO_FLICKER", "1"],
    ["CLAUDE_CONFIG_DIR", claudexHome]
  ]);
  const claudemixEnv = renderEnvFile([
    ["ANTHROPIC_BASE_URL", baseUrl],
    ["CLAUDE_CONFIG_DIR", claudemixHome],
    ["ANTHROPIC_DEFAULT_HAIKU_MODEL", state.backgroundModel],
    ["CLAUDE_CODE_ALWAYS_ENABLE_EFFORT", "1"],
    ["CLAUDE_CODE_NO_FLICKER", "1"]
  ]);
  await writeHardened(join(envDir, "claudex.env"), claudexEnv, 0o600);
  await writeHardened(join(envDir, "claudemix.env"), claudemixEnv, 0o600);

  await writeHardened(
    join(binDir, "claudex"),
    renderWrapper("claudex", join(envDir, "claudex.env"), tokenFile),
    0o700
  );
  await writeHardened(
    join(binDir, "claudemix"),
    renderWrapper("claudemix", join(envDir, "claudemix.env"), tokenFile),
    0o700
  );
}

/** Copy `<systemClaudeDir>/.claude.json` into the home minus identity
 *  (oauthAccount/userID), onboarding forced true — mirrors `seedClaudeConfig`. */
async function seedClaudeJson(home: string, systemClaudeDir: string): Promise<void> {
  let sys: Record<string, unknown>;
  try {
    sys = JSON.parse(await readFile(join(systemClaudeDir, ".claude.json"), "utf8")) as Record<string, unknown>;
  } catch {
    return; // no system config to seed from
  }
  const homeFile = join(home, ".claude.json");
  let existing: Record<string, unknown> | null = null;
  try {
    existing = JSON.parse(await readFile(homeFile, "utf8")) as Record<string, unknown>;
  } catch {
    existing = null; // first seed
  }
  let next: Record<string, unknown>;
  if (!existing || Object.keys(existing).length === 0) {
    next = { ...sys };
    delete next.oauthAccount;
    delete next.userID;
    next.hasCompletedOnboarding = true;
  } else {
    next = { ...existing, mcpServers: sys.mcpServers ?? existing.mcpServers ?? {}, hasCompletedOnboarding: true };
  }
  const serialized = JSON.stringify(next);
  if (JSON.stringify(existing) === serialized) return; // idempotent
  await writeFile(homeFile, serialized, { mode: 0o600 });
}

async function ensureSymlink(target: string, linkPath: string): Promise<void> {
  try {
    await lstat(linkPath);
    return; // already present — leave it
  } catch {
    /* absent */
  }
  try {
    await lstat(target); // only link to something that exists
  } catch {
    return;
  }
  await symlink(target, linkPath).catch(() => undefined);
}

async function copyIfMissing(src: string, dst: string): Promise<void> {
  try {
    await lstat(dst);
    return; // already there
  } catch {
    /* absent */
  }
  let content: string;
  try {
    content = await readFile(src, "utf8");
  } catch {
    return; // nothing to seed
  }
  await writeFile(dst, content, { mode: 0o600 });
}

/**
 * Seed a per-entry managed Claude home (0700) with a `.orq-cliproxy-home` marker
 * (content = entryId): identity-free `.claude.json`, live-shared `skills/` +
 * `plugins/` symlinks, and a one-time `settings.json`. **Never** touches
 * `projects/` — cross-entry transcript isolation is the whole point (spec §2).
 * Refuses a symlinked home and validates the marker on re-entry.
 */
export async function seedHome(
  daemonDir: string,
  entryId: "claudex" | "claudemix",
  systemClaudeDir: string
): Promise<void> {
  const home = cliproxyHomeDir(daemonDir, entryId);
  const markerPath = join(home, CLIPROXY_HOME_MARKER);

  let st: Awaited<ReturnType<typeof lstat>> | null = null;
  try {
    st = await lstat(home);
  } catch {
    st = null;
  }
  if (st) {
    if (st.isSymbolicLink()) {
      throw new Error(`cliproxy home is a symlink: ${entryId}`);
    }
    let marker: string;
    try {
      marker = (await readFile(markerPath, "utf8")).trim();
    } catch {
      throw new Error(`cliproxy home marker missing: ${entryId}`);
    }
    if (marker !== entryId) {
      throw new Error(`cliproxy home marker mismatch: ${entryId}`);
    }
  } else {
    await mkdir(home, { recursive: true, mode: 0o700 });
    await chmod(home, 0o700).catch(() => undefined);
    await writeFile(markerPath, entryId, { mode: 0o600 });
  }

  await seedClaudeJson(home, systemClaudeDir);
  await ensureSymlink(join(systemClaudeDir, "skills"), join(home, "skills"));
  await ensureSymlink(join(systemClaudeDir, "plugins"), join(home, "plugins"));
  await copyIfMissing(join(systemClaudeDir, "settings.json"), join(home, "settings.json"));
}
