import { randomUUID } from "node:crypto";
import { chmod, lstat, mkdir, readFile, realpath, rename, rm, symlink, writeFile } from "node:fs/promises";
import { basename, dirname, join } from "node:path";
import {
  type CliProxySecrets,
  type CliProxyState,
  MODEL_NAME_RE,
  cliproxyDir,
  cliproxyHomeDir,
  cliproxyTokenFile,
  getRouterKey
} from "@orquester/config";

/** Marker file written into each managed home; content is the entry id. */
export const CLIPROXY_HOME_MARKER = ".orq-cliproxy-home";

/**
 * Atomic 0600/0700 write that refuses to be redirected through a symlinked
 * target (parent realpath-canonicalized, final path rebuilt from real parent).
 */
export async function writeHardened(file: string, content: string, mode: number, dirMode = 0o700): Promise<void> {
  const parent = dirname(file);
  await mkdir(parent, { recursive: true, mode: dirMode });
  const realParent = await realpath(parent);
  const target = join(realParent, basename(file));
  let st: Awaited<ReturnType<typeof lstat>> | null = null;
  try {
    st = await lstat(target);
  } catch {
    st = null;
  }
  if (st?.isSymbolicLink()) {
    throw new Error(`refusing to write through a symlinked target: ${file}`);
  }
  const tmp = `${target}.${randomUUID()}.tmp`;
  try {
    await writeFile(tmp, content, { encoding: "utf8", mode });
    await chmod(tmp, mode).catch(() => undefined);
    await rename(tmp, target);
  } catch (error) {
    await rm(tmp, { force: true }).catch(() => undefined);
    throw error;
  }
}

function assertModel(name: string, label: string): void {
  if (!MODEL_NAME_RE.test(name)) {
    throw new Error(`invalid ${label} model name: ${JSON.stringify(name)}`);
  }
}

/** The model id the Fable `/model` slot and the managed `kimi` subagent pin. */
const KIMI_PICK = "kimi-k3";

/** The model id the managed `grok` subagent pins — the coding-trained half of the
 *  curated xAI pair (`grok-4.5` forces reasoning, which stalls Claude Code's
 *  non-streaming classifier call). The Fable `/model` slot stays kimi's. */
const GROK_PICK = "grok-build-0.1";

/** The router provider (if any) that is keyed AND serves the `kimi-k3` pick,
 *  by full name or alias. Drives the Fable slot's label. */
function kimiProvider(state: CliProxyState, secrets: CliProxySecrets): { label: string } | undefined {
  return state.routerProviders.find(
    (p) =>
      getRouterKey(secrets.routerKeys, p.id) !== undefined &&
      p.models.some((m) => m.name === KIMI_PICK || m.alias === KIMI_PICK)
  );
}

/** True when some keyed router provider serves the `kimi-k3` pick (name or alias) —
 *  the Fable-slot / managed-kimi gate, preserving the legacy OpenRouter behavior. */
export function routerKimiAvailable(state: CliProxyState, secrets: CliProxySecrets): boolean {
  return kimiProvider(state, secrets) !== undefined;
}

/**
 * Render the proxy's `config.yaml`. The proxy runs with cwd = the cliproxy dir,
 * so `auth-dir`/log paths are relative. Every user-defined router provider that
 * has a stored API key and at least one model becomes an `openai-compatibility`
 * entry — no key (or no models) means no entry and no aliases. The legacy
 * `secrets.openRouterKey` is NOT read here; the manager migrates it into a
 * `routerProviders` record (it stays on disk only as a rollback mirror).
 */
export function renderConfigYaml(secrets: CliProxySecrets, state: CliProxyState): string {
  const lines: string[] = [
    "# generated by orquester CliProxyManager — do not edit",
    'host: "127.0.0.1"',
    `port: ${state.port}`,
    'auth-dir: "auth"',
    "logging:",
    '  dir: "logs"',
    "  request-log: true",
    // request/response BODIES stay off — they would capture prompts + completions.
    "  log-request-body: false",
    "  log-response-body: false",
    "remote-management:",
    `  secret-key: ${JSON.stringify(secrets.managementSecret)}`,
    "  allow-remote: false",
    "api-keys:",
    `  - ${JSON.stringify(secrets.apiKey)}`
  ];
  const keyed = state.routerProviders
    .map((p) => ({ p, key: getRouterKey(secrets.routerKeys, p.id) }))
    .filter((e): e is { p: (typeof e)["p"]; key: string } => e.key !== undefined && e.p.models.length > 0);
  if (keyed.length > 0) {
    lines.push("openai-compatibility:");
    for (const { p, key } of keyed) {
      lines.push(
        `  - name: ${JSON.stringify(p.id)}`,
        `    base-url: ${JSON.stringify(p.baseUrl)}`,
        "    api-key-entries:",
        `      - api-key: ${JSON.stringify(key)}`,
        // `models` is a PROVIDER-level key (sibling of api-key-entries). Nested
        // under an entry it parses fine but registers ZERO models — the provider
        // loads and every request 502s "unknown provider for model <alias>".
        "    models:"
      );
      for (const m of p.models) {
        lines.push(`      - name: ${JSON.stringify(m.name)}`);
        if (m.alias) lines.push(`        alias: ${JSON.stringify(m.alias)}`);
      }
    }
  }
  return lines.join("\n") + "\n";
}

function renderEnvFile(entries: Array<[string, string]>): string {
  return entries.map(([k, v]) => `${k}=${v}`).join("\n") + "\n";
}

/** Collapse a user-supplied provider label to one safe env-file line: a newline
 *  would append a forged `KEY=VALUE` row, and other control chars are noise. */
function envSafeLabel(label: string): string {
  const cleaned = label.replace(/[\u0000-\u001f\u007f]+/g, " ").trim();
  return cleaned.slice(0, 64) || "router";
}

/** POSIX-sh wrapper for MANUAL shell use only (not the Orquester launch path): parses
 *  the env file as data (no `source`), reads the token file, and (for claudex) accepts a
 *  validated `--model`, then `exec claude`. Kept consistent with the launch env file. */
function renderWrapper(entryId: "claudex" | "claudemix", envFile: string, tokenFile: string): string {
  return [
    "#!/bin/sh",
    "# generated by orquester CliProxyManager — do not edit",
    "set -eu",
    `ENV_FILE="${envFile}"; TOKEN_FILE="${tokenFile}"`,
    "while IFS='=' read -r k v; do",
    "  case \"$k\" in ''|'#'*) continue;; esac",
    "  case \"$k\" in *[!A-Za-z0-9_]*) continue;; esac",
    '  export "$k=$v"',
    'done < "$ENV_FILE"',
    'ANTHROPIC_AUTH_TOKEN="$(cat "$TOKEN_FILE")"; export ANTHROPIC_AUTH_TOKEN',
    `if [ "${entryId}" = "claudex" ] && [ "\${1:-}" = "--model" ]; then`,
    "  case \"${2:-}\" in *[!A-Za-z0-9._/-]*|'') echo \"claudex: invalid --model\" >&2; exit 2;; esac",
    '  export ANTHROPIC_MODEL="$2"; shift 2',
    "fi",
    'exec claude "$@"',
    ""
  ].join("\n");
}

/**
 * Rewrite every derived projection from the authoritative secrets + state:
 * `config.yaml` (0600), `token` (0600), both entry env files under
 * `<daemonDir>/env/` (0600 in a 0700 dir), and both wrapper bins under
 * `<appdir>/.npm-global/bin/` (0700). Model names are validated before any
 * write, so a poisoned model can never reach an env file or shell.
 */
export async function writeProjections(
  daemonDir: string,
  secrets: CliProxySecrets,
  state: CliProxyState
): Promise<void> {
  assertModel(state.defaultModel, "default");
  assertModel(state.backgroundModel, "background");
  // Router model names/aliases reach config.yaml (and, via the Fable slot, an
  // env file) — validate them on the same charset before any write.
  for (const p of state.routerProviders) {
    for (const m of p.models) {
      assertModel(m.name, `router ${p.id}`);
      if (m.alias) assertModel(m.alias, `router ${p.id} alias`);
    }
  }

  const dir = cliproxyDir(daemonDir);
  const baseUrl = `http://127.0.0.1:${state.port}`;
  const appdir = dirname(daemonDir);
  const binDir = join(appdir, ".npm-global", "bin");
  const envDir = join(daemonDir, "env");
  const tokenFile = cliproxyTokenFile(daemonDir);
  const claudexHome = cliproxyHomeDir(daemonDir, "claudex");
  const claudemixHome = cliproxyHomeDir(daemonDir, "claudemix");
  // Provider labels are free-form user text that lands in an env-file VALUE;
  // a newline in one would smuggle an extra `KEY=VALUE` row into claudex.env.
  const kimiFound = kimiProvider(state, secrets);
  const kimiServer = kimiFound ? { label: envSafeLabel(kimiFound.label) } : undefined;

  await writeHardened(join(dir, "config.yaml"), renderConfigYaml(secrets, state), 0o600);
  await writeHardened(tokenFile, `${secrets.apiKey}\n`, 0o600);

  const claudexEnv = renderEnvFile([
    ["ANTHROPIC_BASE_URL", baseUrl],
    ["ANTHROPIC_MODEL", state.defaultModel],
    ["ANTHROPIC_DEFAULT_HAIKU_MODEL", state.backgroundModel],
    ["ANTHROPIC_DEFAULT_HAIKU_MODEL_NAME", state.backgroundModel],
    ["ANTHROPIC_DEFAULT_HAIKU_MODEL_DESCRIPTION", "Background model (via proxy)"],
    // Remap the /model picker's named slots to the curated GPT set: the stock
    // Claude tier rows are dead ends in the GPT launcher (they'd send Claude
    // model ids through the Codex credential). Kimi rides the Fable slot only
    // while some keyed router provider serves it.
    ["ANTHROPIC_DEFAULT_OPUS_MODEL", "gpt-5.6-sol"],
    ["ANTHROPIC_DEFAULT_OPUS_MODEL_NAME", "GPT-5.6 Sol"],
    ["ANTHROPIC_DEFAULT_OPUS_MODEL_DESCRIPTION", "OpenAI flagship — deepest reasoning"],
    ["ANTHROPIC_DEFAULT_SONNET_MODEL", "gpt-5.6-terra"],
    ["ANTHROPIC_DEFAULT_SONNET_MODEL_NAME", "GPT-5.6 Terra"],
    ["ANTHROPIC_DEFAULT_SONNET_MODEL_DESCRIPTION", "Balanced everyday coding"],
    ...(kimiServer
      ? ([
          ["ANTHROPIC_DEFAULT_FABLE_MODEL", KIMI_PICK],
          ["ANTHROPIC_DEFAULT_FABLE_MODEL_NAME", "Kimi K3"],
          ["ANTHROPIC_DEFAULT_FABLE_MODEL_DESCRIPTION", `Moonshot Kimi via ${kimiServer.label}`]
        ] as Array<[string, string]>)
      : []),
    // No CLAUDE_CODE_SUBAGENT_MODEL pin: unset, subagents inherit the session's
    // CURRENT model — so /model switches carry over. A pin to defaultModel left
    // subagents on gpt-5.6-sol (~200k window) after the main loop moved to
    // kimi-k3 (1M), and a large subagent died with "Prompt is too long".
    ["CLAUDE_CODE_ALWAYS_ENABLE_EFFORT", "1"],
    ["CLAUDE_CODE_MAX_TOOL_USE_CONCURRENCY", "3"],
    // Deferred/on-demand tool loading is auto-disabled on a non-first-party
    // ANTHROPIC_BASE_URL; this re-arms it. Safe here because tst mode is fully
    // client-side (ToolSearch is a local tool; deferred tools are omitted from
    // the request) — verified 2026-07-25 end-to-end through CLIProxyAPI
    // v7.2.95+orq1 on all three routes (codex/gpt, openrouter/kimi, claude
    // oauth). Saves the ~50k+ upfront MCP/deferred-tool schema overhead.
    ["ENABLE_TOOL_SEARCH", "true"],
    ["CLAUDE_CODE_NO_FLICKER", "1"],
    ["CLAUDE_CONFIG_DIR", claudexHome]
  ]);
  const claudemixEnv = renderEnvFile([
    ["ANTHROPIC_BASE_URL", baseUrl],
    ["CLAUDE_CONFIG_DIR", claudemixHome],
    ["ANTHROPIC_DEFAULT_HAIKU_MODEL", state.backgroundModel],
    ["ANTHROPIC_DEFAULT_HAIKU_MODEL_NAME", state.backgroundModel],
    ["ANTHROPIC_DEFAULT_HAIKU_MODEL_DESCRIPTION", "Background model (via proxy)"],
    // Claude Code supports exactly ONE additive picker row — spend it on the
    // claudex GPT default. Terra/Kimi stay reachable via free-form `/model`.
    ["ANTHROPIC_CUSTOM_MODEL_OPTION", state.defaultModel],
    ["ANTHROPIC_CUSTOM_MODEL_OPTION_NAME", state.defaultModel],
    ["ANTHROPIC_CUSTOM_MODEL_OPTION_DESCRIPTION", "GPT via the managed proxy"],
    ["CLAUDE_CODE_ALWAYS_ENABLE_EFFORT", "1"],
    // Same rationale as claudex above; covers /model switches too — all three
    // proxy routes tolerate the tst-mode wire shape.
    ["ENABLE_TOOL_SEARCH", "true"],
    ["CLAUDE_CODE_NO_FLICKER", "1"]
  ]);
  await writeHardened(join(envDir, "claudex.env"), claudexEnv, 0o600);
  await writeHardened(join(envDir, "claudemix.env"), claudemixEnv, 0o600);

  // These two wrapper bins are for MANUAL terminal use only — i.e. a person running
  // `claudex`/`claudemix` directly from a shell. The Orquester session-launch path does
  // NOT use them: the claudex/claudemix registry entries declare bin: ["claude"]
  // (packages/registry/src/index.ts), so RegistryService.resolveBin picks the plain
  // `claude` binary, and per-session config is supplied by <daemonDir>/env/<id>.env plus
  // cliproxyContributor (apps/daemon/src/index.ts). They are an intentional, supported
  // convenience surface (pinned by cliproxy-files.test.ts), not dead code.
  await writeHardened(
    join(binDir, "claudex"),
    renderWrapper("claudex", join(envDir, "claudex.env"), tokenFile),
    0o700
  );
  await writeHardened(
    join(binDir, "claudemix"),
    renderWrapper("claudemix", join(envDir, "claudemix.env"), tokenFile),
    0o700
  );
}

/** Copy `<systemClaudeDir>/.claude.json` into the home minus identity
 *  (oauthAccount/userID), onboarding forced true — mirrors `seedClaudeConfig`. */
async function seedClaudeJson(home: string, systemClaudeConfigFile: string): Promise<void> {
  let sys: Record<string, unknown>;
  try {
    sys = JSON.parse(await readFile(systemClaudeConfigFile, "utf8")) as Record<string, unknown>;
  } catch {
    // No system config to copy — still force the onboarding flag, or Claude
    // Code runs its first-run theme/login flow inside the fresh proxy home.
    sys = {};
  }
  const homeFile = join(home, ".claude.json");
  let existing: Record<string, unknown> | null = null;
  try {
    existing = JSON.parse(await readFile(homeFile, "utf8")) as Record<string, unknown>;
  } catch {
    existing = null; // first seed
  }
  let next: Record<string, unknown>;
  if (!existing || Object.keys(existing).length === 0) {
    next = { ...sys };
    delete next.oauthAccount;
    delete next.userID;
    next.hasCompletedOnboarding = true;
  } else {
    next = { ...existing, mcpServers: sys.mcpServers ?? existing.mcpServers ?? {}, hasCompletedOnboarding: true };
  }
  const serialized = JSON.stringify(next);
  if (JSON.stringify(existing) === serialized) return; // idempotent
  await writeFile(homeFile, serialized, { mode: 0o600 });
}

async function ensureSymlink(target: string, linkPath: string): Promise<void> {
  try {
    await lstat(linkPath);
    return; // already present — leave it
  } catch {
    /* absent */
  }
  try {
    await lstat(target); // only link to something that exists
  } catch {
    return;
  }
  await symlink(target, linkPath).catch(() => undefined);
}

async function copyIfMissing(src: string, dst: string): Promise<void> {
  try {
    await lstat(dst);
    return; // already there
  } catch {
    /* absent */
  }
  let content: string;
  try {
    content = await readFile(src, "utf8");
  } catch {
    return; // nothing to seed
  }
  await writeFile(dst, content, { mode: 0o600 });
}

/** Settings keys the daemon owns in every managed proxy home. Force-merged on
 *  every seed pass (enable + boot) so a stale one-time copy can't freeze them
 *  (spec 2026-07-25-compact-parity-design.md §3.1); all other keys — user
 *  edits, theme, hooks — are preserved. */
const MANAGED_HOME_SETTINGS: Record<string, unknown> = { autoCompactEnabled: true };

/** Env keys scrubbed from a managed home's settings.json `env` block on every
 *  seed pass. Model/endpoint routing belongs to the launcher env exclusively;
 *  a copy of the SYSTEM settings.json (one-time `copyIfMissing` seed) can
 *  smuggle these in and silently override it — a leaked
 *  CLAUDE_CODE_SUBAGENT_MODEL=opus forced every proxy subagent (including the
 *  gpt/kimi model-pinned agents) onto claude-opus-5 in production
 *  (2026-07-25). Non-routing keys (MCP_TIMEOUT, …) are preserved. */
const SCRUBBED_SETTINGS_ENV_KEYS = [
  "CLAUDE_CODE_SUBAGENT_MODEL",
  "ANTHROPIC_MODEL",
  "ANTHROPIC_BASE_URL",
  "ANTHROPIC_AUTH_TOKEN",
  "ANTHROPIC_API_KEY",
  "ANTHROPIC_DEFAULT_OPUS_MODEL",
  "ANTHROPIC_DEFAULT_SONNET_MODEL",
  "ANTHROPIC_DEFAULT_HAIKU_MODEL",
  "ANTHROPIC_DEFAULT_FABLE_MODEL",
  "ANTHROPIC_CUSTOM_MODEL_OPTION"
];

async function mergeManagedSettings(home: string): Promise<void> {
  const file = join(home, "settings.json");
  let existing: Record<string, unknown> = {};
  try {
    const parsed = JSON.parse(await readFile(file, "utf8"));
    if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
      existing = parsed as Record<string, unknown>;
    }
  } catch {
    // absent or malformed — managed keys alone become the file
  }
  const next = { ...existing, ...MANAGED_HOME_SETTINGS };
  const env = next.env;
  if (env && typeof env === "object" && !Array.isArray(env)) {
    const scrubbed = { ...(env as Record<string, unknown>) };
    for (const key of SCRUBBED_SETTINGS_ENV_KEYS) delete scrubbed[key];
    next.env = scrubbed;
  }
  if (JSON.stringify(next) === JSON.stringify(existing)) return; // no write churn
  await writeFile(file, JSON.stringify(next, null, 2), { mode: 0o600 });
}

/** Model-pinned subagent definitions rewritten into every managed home's
 *  `agents/` on each seed pass, so e.g. `subagent_type: "gpt-luna"` runs that
 *  subagent on the pinned proxy model. Agent frontmatter `model:` is the only
 *  per-subagent model mechanism Claude Code supports, and it accepts arbitrary
 *  ids (verified 2026-07-25 through the proxy on all three routes: main on
 *  fable, subagents on luna/kimi). Gated entries follow the credential that can
 *  actually serve them — `kimi` a keyed router serving `kimi-k3`, `grok` a linked
 *  xAI OAuth account; an unknown gate state leaves the file as-is. User agents
 *  under other filenames are never touched. */
const MANAGED_AGENTS: Array<{
  file: string;
  name: string;
  model: string;
  blurb: string;
  gate?: "kimi" | "xai";
}> = [
  { file: "gpt-sol.md", name: "gpt-sol", model: "gpt-5.6-sol", blurb: "GPT-5.6 Sol (OpenAI flagship — deepest reasoning)" },
  { file: "gpt-terra.md", name: "gpt-terra", model: "gpt-5.6-terra", blurb: "GPT-5.6 Terra (balanced everyday coding)" },
  { file: "gpt-luna.md", name: "gpt-luna", model: "gpt-5.6-luna", blurb: "GPT-5.6 Luna (fast, low cost)" },
  { file: "kimi.md", name: "kimi", model: KIMI_PICK, blurb: "Kimi K3 via the configured router (1M-token context)", gate: "kimi" },
  { file: "grok.md", name: "grok", model: GROK_PICK, blurb: "Grok Build via the linked xAI account (256k context, coding-trained)", gate: "xai" }
];

function renderManagedAgent(agent: (typeof MANAGED_AGENTS)[number]): string {
  return [
    "---",
    `name: ${agent.name}`,
    `description: General-purpose subagent pinned to ${agent.blurb} through the managed proxy. Use when asked to delegate work to this model, or for a cross-model second opinion.`,
    `model: ${agent.model}`,
    "---",
    "",
    "<!-- orq-managed: rewritten on every daemon seed pass; edits will be lost. -->",
    "",
    `You are a general-purpose subagent running on ${agent.model}. Complete the delegated task with the available tools. Your final message is returned verbatim to the orchestrator, so end it with the concrete results.`,
    ""
  ].join("\n");
}

/** Claudemix-only managed user memory (`<home>/CLAUDE.md`, loaded into every
 *  session of that home): tells the orchestrating Claude how to reach the
 *  non-Claude models — without it, models improvise (codex/opencode CLIs,
 *  pkill) instead of using the seeded subagent types. Claudex needs no note:
 *  its main loop already IS the GPT set. Skipped while the router key
 *  state is unknown so kimi mentions can't flap on a secrets-less boot. */
function renderManagedMemory(kimiAvailable: boolean, xaiLinked: boolean): string {
  const kimiAgent = kimiAvailable ? ', "kimi" (Kimi K3 — 1M-token context via the router)' : "";
  const kimiModel = kimiAvailable ? `, ${KIMI_PICK}` : "";
  const grokAgent = xaiLinked ? ', "grok" (Grok Build — xAI, 256k context)' : "";
  const grokModel = xaiLinked ? `, ${GROK_PICK}` : "";
  const extra = [kimiAvailable ? "Kimi" : null, xaiLinked ? "Grok" : null].filter((p) => p !== null);
  return [
    "<!-- orq-managed: rewritten on every daemon seed pass; edits will be lost. -->",
    "",
    ["# Model proxy: delegating to GPT", ...extra].join(" / "),
    "",
    "This session runs through the Orquester model proxy, which also serves",
    "non-Claude models:",
    "",
    "- To run a SUBAGENT on another model, call the Task tool with one of these",
    `  subagent_type values: "gpt-sol" (GPT-5.6 Sol — deepest reasoning),`,
    `  "gpt-terra" (balanced), "gpt-luna" (fast, low cost)${kimiAgent}${grokAgent}.`,
    "  Subagents spawned with any other type inherit the session's current main",
    "  model.",
    `- To switch the MAIN loop, /model accepts: gpt-5.6-sol, gpt-5.6-terra,`,
    `  gpt-5.6-luna${kimiModel}${grokModel}.`,
    "- Never try to reach these models through codex/opencode CLIs or raw APIs —",
    "  the subagent types and /model ids above are the only supported path.",
    ""
  ].join("\n");
}

async function seedManagedMemory(
  home: string,
  entryId: "claudex" | "claudemix",
  kimiAvailable: boolean | undefined,
  xaiLinked: boolean | undefined
): Promise<void> {
  if (entryId !== "claudemix" || kimiAvailable === undefined) return;
  const file = join(home, "CLAUDE.md");
  // The xai gate is derived from the auth dir (no secrets needed), so the manager
  // always knows it; an `undefined` from another caller just omits the grok lines
  // rather than blocking the whole file on it.
  const content = renderManagedMemory(kimiAvailable, xaiLinked === true);
  try {
    if ((await readFile(file, "utf8")) === content) return; // no write churn
  } catch {
    /* absent */
  }
  await writeFile(file, content, { mode: 0o600 });
}

async function seedManagedAgents(
  home: string,
  kimiAvailable: boolean | undefined,
  xaiLinked: boolean | undefined
): Promise<void> {
  const dir = join(home, "agents");
  await mkdir(dir, { recursive: true });
  for (const agent of MANAGED_AGENTS) {
    const file = join(dir, agent.file);
    if (agent.gate) {
      const available = agent.gate === "kimi" ? kimiAvailable : xaiLinked;
      if (available === undefined) continue; // gate state unknown — don't churn
      if (!available) {
        await rm(file, { force: true });
        continue;
      }
    }
    const content = renderManagedAgent(agent);
    try {
      if ((await readFile(file, "utf8")) === content) continue; // no write churn
    } catch {
      /* absent */
    }
    await writeFile(file, content, { mode: 0o600 });
  }
}

/**
 * Seed a per-entry managed Claude home (0700) with a `.orq-cliproxy-home` marker
 * (content = entryId): identity-free `.claude.json`, live-shared `skills/` +
 * `plugins/` symlinks, and a one-time `settings.json` copy with the managed
 * keys force-merged on top. **Never** touches
 * `projects/` — cross-entry transcript isolation is the whole point (spec §2).
 * Refuses a symlinked home and validates the marker on re-entry.
 */
export async function seedHome(
  daemonDir: string,
  entryId: "claudex" | "claudemix",
  systemClaudeDir: string,
  // The system `.claude.json` sits at HOME level (sibling of ~/.claude), NOT
  // inside the config dir, unless CLAUDE_CONFIG_DIR relocates it — same
  // resolution as agent-accounts. Passed explicitly so the two layouts can't
  // be conflated again (reading `<dir>/.claude.json` silently seeded nothing
  // in production and every proxy session got the onboarding flow).
  systemClaudeConfigFile: string,
  // Whether some keyed router provider serves `kimi-k3` (gates the managed kimi
  // subagent); undefined = secrets not loaded, leave the kimi file untouched.
  // See routerKimiAvailable().
  kimiAvailable?: boolean,
  // Whether an xAI OAuth account is linked (gates the managed grok subagent);
  // undefined = state unknown, leave the grok file untouched. Derived from the
  // proxy's auth dir — see scanXaiAuthFiles()/deriveXaiAccount().
  xaiLinked?: boolean
): Promise<void> {
  const home = cliproxyHomeDir(daemonDir, entryId);
  const markerPath = join(home, CLIPROXY_HOME_MARKER);

  let st: Awaited<ReturnType<typeof lstat>> | null = null;
  try {
    st = await lstat(home);
  } catch {
    st = null;
  }
  if (st) {
    if (st.isSymbolicLink()) {
      throw new Error(`cliproxy home is a symlink: ${entryId}`);
    }
    let marker: string;
    try {
      marker = (await readFile(markerPath, "utf8")).trim();
    } catch {
      throw new Error(`cliproxy home marker missing: ${entryId}`);
    }
    if (marker !== entryId) {
      throw new Error(`cliproxy home marker mismatch: ${entryId}`);
    }
  } else {
    await mkdir(home, { recursive: true, mode: 0o700 });
    await chmod(home, 0o700).catch(() => undefined);
    await writeFile(markerPath, entryId, { mode: 0o600 });
  }

  await seedClaudeJson(home, systemClaudeConfigFile);
  await ensureSymlink(join(systemClaudeDir, "skills"), join(home, "skills"));
  await ensureSymlink(join(systemClaudeDir, "plugins"), join(home, "plugins"));
  await copyIfMissing(join(systemClaudeDir, "settings.json"), join(home, "settings.json"));
  await mergeManagedSettings(home);
  await seedManagedAgents(home, kimiAvailable, xaiLinked);
  await seedManagedMemory(home, entryId, kimiAvailable, xaiLinked);
}
