import { chmod, mkdir, readFile, rename, rm, stat, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { decodeJwtPayload, grokAuthEntry } from "./agent-account-identity.ts";

/**
 * The one-time handover from the removed model proxy (CLIProxyAPI, which backed
 * the retired `claudex`/`claudemix` launchers).
 *
 * The proxy ran in the `orqsvc-cliproxy` tmux service session, so it survives
 * the deploy that removed it and would go on refreshing the accounts seeded
 * into it. OAuth refresh tokens are single-use: while the proxy and the
 * accounts refresher both refresh one account, whichever goes second logs the
 * account out. So, before anything else refreshes:
 *
 *  1. the proxy's service session is killed (a tmux-less host ran it as a
 *     daemon child, which died with the old daemon);
 *  2. for every account the proxy held, its copy of the token pair is written
 *     back to the managed home when it is the fresher one (the proxy refreshed
 *     last) — the managed home is the only copy from now on;
 *  3. the generated launcher env files and manual-use wrapper bins are removed
 *     (they carry the proxy's token and name a server that no longer runs).
 *
 * The accounts' `proxyOwned` flag needs no step: the accounts schema no longer
 * knows it, so it is dropped on the next load and the refresher owns them all.
 * `<daemonDir>/cliproxy/` itself (router keys, the proxy's credential copies,
 * the binary) is left where it is — the user's data, deleted by hand — and a
 * `retired` marker in it makes every later boot skip this. Best-effort
 * throughout: a failure is logged and never blocks the boot.
 */
export async function retireModelProxy(opts: {
  daemonDir: string;
  /** Kill a tmux service session; absent on a tmux-less host. */
  killServiceSession?: (name: string) => Promise<void>;
  /** A managed account's credential file (claude `.credentials.json`, codex/grok `auth.json`). */
  managedCredentialPath(provider: SeededProvider, accountId: string): string;
}): Promise<void> {
  const dir = join(opts.daemonDir, "cliproxy");
  const marker = join(dir, "retired");
  if (!(await exists(dir)) || (await exists(marker))) return;

  // First, so the proxy cannot refresh a token between the read and the write-back.
  await opts.killServiceSession?.(PROXY_SERVICE_SESSION).catch(() => undefined);

  for (const account of await seededAccounts(join(dir, "state.json"))) {
    try {
      await handBack(join(dir, "auth", authFileName(account)), opts.managedCredentialPath(account.provider, account.accountId), account.provider);
    } catch (error) {
      console.error(`model proxy retirement: handing back ${account.provider} account ${account.accountId} failed`, error);
    }
  }

  const envDir = join(opts.daemonDir, "env");
  const binDir = join(dirname(opts.daemonDir), ".npm-global", "bin");
  for (const id of ["claudex", "claudemix"]) {
    await rm(join(envDir, `${id}.env`), { force: true }).catch(() => undefined);
    await removeGeneratedWrapper(join(binDir, id));
  }

  await writeFile(
    marker,
    "The model proxy was removed from Orquester. Nothing reads this directory any more; delete it when you like.\n"
  ).catch((error) => console.error("model proxy retirement: writing the marker failed", error));
}

type SeededProvider = "codex" | "claude" | "grok";
interface SeededAccount {
  provider: SeededProvider;
  accountId: string;
}

const PROXY_SERVICE_SESSION = "orqsvc-cliproxy";
const WRAPPER_MARKER = "# generated by orquester CliProxyManager";

async function exists(path: string): Promise<boolean> {
  try {
    await stat(path);
    return true;
  } catch {
    return false;
  }
}

/** The proxy's `state.seededAccounts`, read loosely: a bad entry is skipped. */
async function seededAccounts(stateFile: string): Promise<SeededAccount[]> {
  let raw: unknown;
  try {
    raw = JSON.parse(await readFile(stateFile, "utf8"));
  } catch {
    return [];
  }
  const list = isRecord(raw) && Array.isArray(raw.seededAccounts) ? raw.seededAccounts : [];
  const out: SeededAccount[] = [];
  for (const entry of list) {
    if (!isRecord(entry)) continue;
    const { provider, accountId } = entry;
    if ((provider === "codex" || provider === "claude" || provider === "grok") && typeof accountId === "string" && /^[\w-]+$/.test(accountId)) {
      out.push({ provider, accountId });
    }
  }
  return out;
}

/** The proxy's auth file name for a seeded account (`acc<first 8 hex of the id>`). */
function authFileName({ provider, accountId }: SeededAccount): string {
  const prefix = `acc${accountId.replace(/-/g, "").slice(0, 8)}`;
  return provider === "grok" ? `xai-${prefix}.json` : `${provider}-${prefix}.json`;
}

/**
 * Write the proxy's token pair into the managed credential when the proxy's
 * access token expires later (it refreshed last). Everything else in the
 * managed file is kept. Equal or undecidable expiries leave the managed copy.
 */
async function handBack(authFile: string, credPath: string, provider: SeededProvider): Promise<void> {
  let proxy: unknown;
  let managed: unknown;
  try {
    proxy = JSON.parse(await readFile(authFile, "utf8"));
    managed = JSON.parse(await readFile(credPath, "utf8"));
  } catch {
    return; // either copy missing or unreadable — nothing to converge
  }
  if (!isRecord(proxy) || !isRecord(managed)) return;
  const access = typeof proxy.access_token === "string" ? proxy.access_token : "";
  const expiry = typeof proxy.expired === "string" ? Date.parse(proxy.expired) : NaN;
  if (!access || !Number.isFinite(expiry)) return;
  const refresh = typeof proxy.refresh_token === "string" && proxy.refresh_token ? proxy.refresh_token : null;

  let next: Record<string, unknown>;
  if (provider === "claude") {
    if (!isRecord(managed.claudeAiOauth)) return;
    const oauth = managed.claudeAiOauth;
    if (oauth.accessToken === access || !laterThan(expiry, oauth.expiresAt)) return;
    next = { ...managed, claudeAiOauth: { ...oauth, accessToken: access, expiresAt: expiry, ...(refresh ? { refreshToken: refresh } : {}) } };
  } else if (provider === "grok") {
    const entry = grokAuthEntry(managed);
    const key = Object.keys(managed).find((k) => managed[k] === entry);
    if (!entry || !key || entry.key === access) return;
    const managedExpiry = typeof entry.expires_at === "string" ? Date.parse(entry.expires_at) : NaN;
    if (!laterThan(expiry, managedExpiry)) return;
    next = {
      ...managed,
      [key]: {
        ...entry,
        key: access,
        expires_at: new Date(expiry).toISOString(),
        ...(refresh ? { refresh_token: refresh } : {}),
        ...(typeof proxy.last_refresh === "string" && proxy.last_refresh ? { create_time: proxy.last_refresh } : {})
      }
    };
  } else {
    if (!isRecord(managed.tokens)) return;
    const tokens = managed.tokens;
    if (tokens.access_token === access) return;
    const exp = typeof tokens.access_token === "string" ? decodeJwtPayload(tokens.access_token)?.exp : undefined;
    if (!laterThan(expiry, typeof exp === "number" ? exp * 1000 : NaN)) return;
    next = {
      ...managed,
      tokens: {
        ...tokens,
        access_token: access,
        ...(refresh ? { refresh_token: refresh } : {}),
        ...(typeof proxy.id_token === "string" && proxy.id_token ? { id_token: proxy.id_token } : {})
      },
      ...(typeof proxy.last_refresh === "string" && proxy.last_refresh ? { last_refresh: proxy.last_refresh } : {})
    };
  }
  await writeAtomic0600(credPath, JSON.stringify(next));
}

function laterThan(proxyExpiry: number, managedExpiry: unknown): boolean {
  return typeof managedExpiry !== "number" || !Number.isFinite(managedExpiry) || proxyExpiry > managedExpiry;
}

async function writeAtomic0600(path: string, content: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  const tmp = `${path}.${process.pid}.${Date.now()}.tmp`;
  await writeFile(tmp, content, { mode: 0o600 });
  await chmod(tmp, 0o600);
  await rename(tmp, path);
}

/** Remove a wrapper bin only when the proxy generated it. */
async function removeGeneratedWrapper(path: string): Promise<void> {
  try {
    if ((await readFile(path, "utf8")).includes(WRAPPER_MARKER)) await rm(path, { force: true });
  } catch {
    /* absent or unreadable — not ours to touch */
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
