import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { retireModelProxy } from "./model-proxy-retirement.ts";

const GROK_ID = "b9682f5c-425a-4c53-be6e-28de477be6c7";
const CODEX_ID = "65eebd90-01d1-4063-b743-c4a5713f5519";
const CLAUDE_ID = "11112222-3333-4444-5555-666677778888";
const GROK_KEY = "https://auth.x.ai::b1a00492-073a-47ea-816f-4c329264a828";

function jwt(claims: Record<string, unknown>): string {
  return `h.${Buffer.from(JSON.stringify(claims)).toString("base64url")}.s`;
}

async function exists(path: string): Promise<boolean> {
  return stat(path).then(
    () => true,
    () => false
  );
}

async function setup() {
  const appdir = await mkdtemp(join(tmpdir(), "orq-retire-"));
  const daemonDir = join(appdir, "daemon");
  const proxyDir = join(daemonDir, "cliproxy");
  await mkdir(join(proxyDir, "auth"), { recursive: true });
  await mkdir(join(daemonDir, "env"), { recursive: true });
  await mkdir(join(appdir, ".npm-global", "bin"), { recursive: true });
  const cred = (provider: string, id: string) =>
    join(daemonDir, "accounts", provider, id, provider === "claude" ? ".credentials.json" : "auth.json");
  const write = async (path: string, value: unknown) => {
    await mkdir(join(path, ".."), { recursive: true });
    await writeFile(path, typeof value === "string" ? value : JSON.stringify(value));
  };
  await write(join(proxyDir, "state.json"), {
    seededAccounts: [
      { provider: "grok", accountId: GROK_ID, label: "g", prefix: "x" },
      { provider: "codex", accountId: CODEX_ID, label: "c", prefix: "x" },
      { provider: "claude", accountId: CLAUDE_ID, label: "a", prefix: "x" },
      { provider: "bogus", accountId: "zzz" }
    ]
  });
  return { appdir, daemonDir, proxyDir, cred, write };
}

test("the proxy's fresher tokens are handed back, its launcher files removed, and it runs once", async () => {
  const h = await setup();
  const later = "2026-10-01T12:00:00Z";
  const earlier = "2026-09-01T12:00:00Z";

  // grok: the proxy refreshed last — its pair wins.
  await h.write(join(h.proxyDir, "auth", "xai-accb9682f5c.json"), {
    access_token: "proxy-at",
    refresh_token: "proxy-rt",
    expired: later
  });
  await h.write(h.cred("grok", GROK_ID), {
    [GROK_KEY]: { key: "home-at", refresh_token: "home-rt", expires_at: earlier, email: "g@example.com" }
  });
  // codex: the managed home refreshed last — left alone.
  await h.write(join(h.proxyDir, "auth", "codex-acc65eebd90.json"), {
    access_token: "proxy-codex",
    refresh_token: "proxy-codex-rt",
    expired: earlier
  });
  const codexHome = { tokens: { access_token: jwt({ exp: Date.parse(later) / 1000 }), refresh_token: "home-codex-rt" } };
  await h.write(h.cred("codex", CODEX_ID), codexHome);
  // claude: the proxy refreshed last.
  await h.write(join(h.proxyDir, "auth", "claude-acc11112222.json"), {
    access_token: "proxy-claude",
    refresh_token: "proxy-claude-rt",
    expired: later
  });
  await h.write(h.cred("claude", CLAUDE_ID), {
    claudeAiOauth: { accessToken: "home-claude", refreshToken: "home-claude-rt", expiresAt: Date.parse(earlier), scopes: ["x"] }
  });

  await h.write(join(h.daemonDir, "env", "claudex.env"), "A=1\n");
  await h.write(join(h.daemonDir, "env", "opencode.env"), "B=2\n");
  await h.write(join(h.appdir, ".npm-global", "bin", "claudex"), "#!/bin/sh\n# generated by orquester CliProxyManager — do not edit\n");
  await h.write(join(h.appdir, ".npm-global", "bin", "claudemix"), "#!/bin/sh\necho mine\n");

  const killed: string[] = [];
  const opts = {
    daemonDir: h.daemonDir,
    killServiceSession: async (name: string) => void killed.push(name),
    managedCredentialPath: h.cred
  };
  await retireModelProxy(opts);

  assert.deepEqual(killed, ["orqsvc-cliproxy"]);
  const grok = JSON.parse(await readFile(h.cred("grok", GROK_ID), "utf8"));
  assert.equal(grok[GROK_KEY].key, "proxy-at");
  assert.equal(grok[GROK_KEY].refresh_token, "proxy-rt");
  assert.equal(grok[GROK_KEY].expires_at, new Date(later).toISOString());
  assert.equal(grok[GROK_KEY].email, "g@example.com", "the rest of the entry is kept");
  assert.deepEqual(JSON.parse(await readFile(h.cred("codex", CODEX_ID), "utf8")), codexHome);
  const claude = JSON.parse(await readFile(h.cred("claude", CLAUDE_ID), "utf8"));
  assert.equal(claude.claudeAiOauth.accessToken, "proxy-claude");
  assert.equal(claude.claudeAiOauth.refreshToken, "proxy-claude-rt");
  assert.deepEqual(claude.claudeAiOauth.scopes, ["x"]);

  assert.equal(await exists(join(h.daemonDir, "env", "claudex.env")), false);
  assert.equal(await exists(join(h.daemonDir, "env", "opencode.env")), true);
  assert.equal(await exists(join(h.appdir, ".npm-global", "bin", "claudex")), false);
  assert.equal(await exists(join(h.appdir, ".npm-global", "bin", "claudemix")), true, "a file the proxy did not write stays");
  assert.equal(await exists(join(h.proxyDir, "retired")), true);

  // A later boot does nothing.
  await h.write(join(h.proxyDir, "auth", "xai-accb9682f5c.json"), { access_token: "newer", expired: "2027-01-01T00:00:00Z" });
  await retireModelProxy(opts);
  assert.deepEqual(killed, ["orqsvc-cliproxy"]);
  assert.equal(JSON.parse(await readFile(h.cred("grok", GROK_ID), "utf8"))[GROK_KEY].key, "proxy-at");
});

test("no proxy directory: nothing happens", async () => {
  const appdir = await mkdtemp(join(tmpdir(), "orq-retire-none-"));
  const killed: string[] = [];
  await retireModelProxy({
    daemonDir: join(appdir, "daemon"),
    killServiceSession: async (name) => void killed.push(name),
    managedCredentialPath: () => join(appdir, "x")
  });
  assert.deepEqual(killed, []);
  assert.equal(await exists(join(appdir, "daemon")), false);
});
